# Generated by Django 5.2.1 on 2025-05-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicstrip',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
