# Generated by Django 5.2.1 on 2025-05-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comicstrip_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicstrip',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='comicstrip',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='comicstrip',
            name='topic',
        ),
    ]
